fixtures:
  repositories:
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib'
      ref: '3.2.1'
    git:
      repo: 'git://github.com/puppetlabs/puppetlabs-git.git'
      ref: '0.0.3'
    vcsrepo:
      repo: 'git://github.com/puppetlabs/puppetlabs-vcsrepo.git'
      ref: '0.2.0'
    apache:
      repo: 'git://github.com/puppetlabs/puppetlabs-apache.git'
      ref: '1.0.1'
    concat:
      repo: 'git://github.com/puppetlabs/puppetlabs-concat.git'
      ref: '1.0.0'
  symlinks:
    kibana3: "#{source_dir}"
